@startuml
skinparam Handwritten true
skinparam monochrome true	
skinparam shadowing false
node "<size:13>       Infrastructure       </size>" as Infrastructure
node "<size:13>           UI           </size>" as UI
node "<size:13>   Application  </size>" as Application
node "<size:13>     Domain     </size>" as Domain
Infrastructure .down.> UI
Infrastructure .down.> Domain
Infrastructure .down.> Application
UI .down.> Application
Application .down.> Domain
@enduml